AIPlayground/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from user.views import logout, sign_view, login_view, register_view, profile_view
from home.views import home_view
from problem.views import problem_view
from submission.views import submission_view, submit
from status.views import status_view
from tests.views import vue_test

handler404 = 'home.views.page_not_found_view'
handler500 = 'home.views.error_view'
handler403 = 'home.views.permission_denied_view'
handler400 = 'home.views.bad_request_view'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name='home'),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout, name='logout'),
    url(r'^problem/', include('problem.urls')),
    url(r'^competition/', home_view, name='competition'),
    url(r'^board/', home_view, name='board'),
    url(r'^sign/', sign_view, name='sign'),
    url(r'^user/$', home_view, name='user'),
    url(r'^search/$', home_view, name='search')
    # url(r'^problist/', problist_view, name='problist'),
    # url(r'^settings/', include('user.urls', namespace='settings', app_name='user')),
    # url(r'^problem/(\d+)/', problem_view, name='problem'),
    # url(r'^submission/(\d+)', submission_view, name='submission'),
    # url(r'^submit/', submit, name='submit'),
    # url(r'^status/', status_view, name='status'),
    # url(r'^profile/(.+)/', profile_view, name='profile'),
    # url(r'^test/', vue_test)
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

problem/urls.py
from django.conf.urls import url
from .views import problem_feed, problem_view

urlpatterns = [
    url(r'^$', problem_feed, name='problem'),
    url(r'^(\d+)/', problem_view, name='problem_view'),
]

user/urls.py
from django.conf.urls import url
from .views import settings_profile, settings_security

urlpatterns = [
    url(r'^profile/', settings_profile, name='profile'),
    url(r'^security/', settings_security, name='security'),
    # url(r'^notification/', settings_notification, name='notification')
]

home/models.py
from django.db import models

# Create your models here.

problem/models.py
from django.db import models
from django.contrib.auth.models import User


class Sample(models.Model):

    input = models.FileField('Input')
    output = models.FileField('Output')


class Problem(models.Model):
    STATUS_CHOICES = (
        ('r', 'Removed'),
        ('a', 'Available'),
    )

    COMBAT_TYPE_CHOICES = (
        (1, 'Single'),
        (2, 'Combat'),
    )

    id = models.IntegerField('#', primary_key=True)
    title = models.CharField('Title', max_length=70)
    author = models.ForeignKey(User)
    submissions = models.IntegerField('Submissions', default=0)
    status = models.CharField('Status', max_length=1, choices=STATUS_CHOICES)
    likes = models.PositiveIntegerField('Likes', default=0)

    time_limit = models.IntegerField('Time Limit (ms)', default=1000)
    memory_limit = models.IntegerField('Memory Limit (MB)', default=512)
    program_limit = models.IntegerField('Program Limit (KB)', default=128)
    combat_type = models.IntegerField('Combat Type', choices=COMBAT_TYPE_CHOICES, default=1)
    description = models.TextField('Description')
    input = models.TextField('Input')
    output = models.TextField('Output')
    samples = models.ManyToManyField(Sample)

    # judge = models.ForeignKey(Judge, blank=True)

    def __str__(self):
        return str(self.id) + ' - ' + self.title

    class Meta:
        ordering = ['-id']

submission/models.py
from django.db import models
from problem.models import Problem
from django.contrib.auth.models import User

VERDICT_STATUS = (
    (100, 'Waiting'),
    (101, 'Running'),
    (102, 'Pretest Passed (Past)'),
    (129, 'Compiling'),
    (130, 'Compile Error'),
    (131, 'Waiting for Judge'),

    # Status for AI Playground
    (200, 'Locked'),
    (201, 'Pretest Passed'),
    (202, 'Running on Contest'),
    (400, 'Rejected'),

    # Status for Online Judge
    (1000, 'Accepted'),
    (1001, 'Wrong Answer'),
    (1002, 'Time Limit Exceeded'),
    (1003, 'Memory Limit Exceeded'),
    (1004, 'Runtime Error'),
    (1005, 'System Error'),

)


class Submission(models.Model):
    LANG_CHOICES = (
        ('c', 'C++'),
        ('j', 'Java'),
        ('p', 'Python')
    )

    problem = models.ForeignKey(Problem)
    author = models.ForeignKey(User)
    language = models.CharField('Language', max_length=1, choices=LANG_CHOICES)
    code = models.TextField('Code')
    submit_time = models.DateTimeField('Submit Time', auto_now_add=True)

    compile_error = models.TextField('Compile Error Message', null=True, blank=True)
    verdict = models.IntegerField('Verdict', choices=VERDICT_STATUS, null=True, blank=True)
    running_time = models.IntegerField('Running Time (ms)', null=True, blank=True)
    running_memory = models.IntegerField('Running Memory (KB)', null=True, blank=True)
    score = models.IntegerField('Score', default=0)
    rating = models.IntegerField('Rating', default=0)

    def __str__(self):
        return 'Submission #' + str(self.id)


class Round(models.Model):

    # There can be one or two or many (what?) submissions
    # Judge can be found in the related problem of the related submission...
    # A round can be played by one player (typically ACM Problems) or two players (AI Problems)
    submissions = models.ManyToManyField(Submission)

    # The corresponding runs are automatically attached to the round

    # All result can be found here
    # It will be formatted as: Player A scored xxx. Player B scored xxx.
    # The score will be stored temporarily in the submission field when running, and reset when rerunning.
    result = models.TextField('Judge Result', null=True, blank=True)


class Run(models.Model):
    round = models.ForeignKey(Round)
    running_time = models.IntegerField('Running Time (ms)', default=0)
    running_memory = models.IntegerField('Running Memory (KB)', default=0)
    input = models.FileField('Input', null=True, blank=True)
    output = models.FileField('Output', null=True, blank=True)
    message = models.TextField('Run Result Message', null=True, blank=True)
    result = models.IntegerField('Judge Result', choices=VERDICT_STATUS, default=100)

    def __str__(self):
        return 'Round ' + str(self.round.id) + ' #' + str(self.id)

home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home.html', {'nav_home': 'active'})


# The page_not_found() view is overridden by handler404:
# The server_error() view is overridden by handler500:
# The permission_denied() view is overridden by handler403:
# The bad_request() view is overridden by handler400:


def page_not_found_view(request):
    return render(request, 'error.html', {'error_title': 'Page Not Found',
                                          'error_msg': 'Ah oh, you have accidentally stepped into nowhere.'})


def error_view(request):
    return render(request, 'error.html', {'error_title': 'Server Error',
                                          'error_msg': 'What have you done to me?'})


def permission_denied_view(request):
    return render(request, 'error.html', {'error_title': 'Permission Denied',
                                          'error_msg': 'It seems that you are not doing it in the right way.'})


def bad_request_view(request):
    return render(request, 'error.html', {'error_title': 'Bad Request',
                                          'error_msg': 'The request you have sent is too difficult for me to understand.'})

problem/views.py
from django.shortcuts import render
from .models import Problem
import markdown2

CONTEXT = {'nav_problem': 'active'}


def problem_feed(request):
    return render(request, 'feed_problem.html', CONTEXT)


# def problem_view(request, get_id):
#     problem = Problem.objects.get(id=get_id)
#     problem.description = markdown2.markdown(problem.description, )
#     # problem.input = markdown2.markdown(problem.input)
#     # problem.output = markdown2.markdown(problem.output)
#     return render(request, 'problem.html', {'problem': problem, 'problist_active': 'active'})

def problem_view(request, pid):
    return render(request, 'problem.html', CONTEXT)

submission/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import Submission
from .models import Run
from problem.models import Problem


def submission_view(request, get_id):
    submission = Submission.objects.get(id=get_id)
    problem = submission.problem
    return render(request, 'submission.html', {'problem': problem, 'submission': submission})


def submit(request):
    submission = Submission()
    submission.code = request.POST['code']
    submission.language = request.POST['languageSelect']
    submission.problem = Problem.objects.get(id=int(request.POST['problem_id']))
    submission.author = request.user
    submission.save()
    return HttpResponseRedirect(reverse('submission', args=(str(submission.id), )))

templates/base.html
{% load staticfiles %}
{% load static_extra %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0"/>
  <title>{% if title %}{{ title }}{% else %}AI Playground{% endif %}</title>
  <!-- TODO: hard coding -->
  <link rel="icon" href="{% static 'favicon.ico' %}">

  <!-- CSS  -->
  <!-- TODO: with cache -->
  <link href="{% static_no_cache 'css/materialize.css' %}" rel="stylesheet">
  <link href="{% static_no_cache 'css/layout.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}

</head>
<body>

  <div class="base-navbar">
    {% include 'components/navbar.html' %}
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

  {% include 'components/footer.html' %}


  <!--  Scripts -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/vue.js' %}"></script>
  <script src="{% static_no_cache 'js/init.js' %}"></script>
  <script src="{% static 'js/materialize.min.js' %}"></script>

  <!-- Place this tag in your head or just before your close body tag. For github -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  {% block script %}{% endblock %}

  </body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static_extra %}
{% block content %}

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br><br><br>
    <h1 class="header center grey-text text-darken-4">{{ error_title }}</h1>
    <div class="row center">
      <h5 class="header col s12 light">{{ error_msg }}</h5>
    </div>
    <div class="row center">
      <a href="{% url 'home' %}" class="btn-large waves-effect waves-light pink">
        Go to homepage</a>
    </div>
    <br><br><br><br><br><br>
  </div>
</div>



{% endblock %}

{% block script %}

<script src="{% static_no_cache 'js/home.js' %}"></script>

{% endblock %}

templates/feed_problem.html
{% extends 'base.html' %}
{% load static_extra %}
{% load staticfiles %}
{% block content %}
<div class="section">
  <div class="container" id="feed-problem">
    <h2 class="container-header">Problems</h2>
    <div class="row">
      <form class="col s12 m9 offset-m3 l6 offset-l6" v-on:submit.prevent="search">
        <div class="input-field">
          <!-- TODO: add tags -->
          <input id="search-problem" type="search" placeholder="Search for tags, names, authors...">
          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        </div>
      </form>
    </div>

    <ul class="collection feed-collection">
      <li @click="gotoProblem" class="collection-item avatar">
        <img src="{% static 'img/style_imagery_bestpractices_1.png' %}" alt="" class="circle">
        <span class="title">A+B Problem (combat)</span>
        <p>Created by ultmaster.<br>
          My submission: 2 days ago.
        </p>
        <div class="chip">traditional</div>
        <div class="chip">test</div>
        <p class="secondary-content">
          <i class="material-icons md-18">grade</i>
          <i class="material-icons md-18">grade</i>
          <i class="material-icons md-18">grade</i>
          <i class="material-icons md-18">grade</i>
        </p>
      </li>
      <li @click="gotoProblem" class="collection-item avatar">
        <i class="material-icons circle green">folder</i>
        <span class="title">Mr. Panda and his fantastic beasts</span>
        <p>Created by Google.<br>
           3 submissions so far.
        </p>
        <div class="chip">ACM</div>
        <div class="chip">fantastic problems</div>
        <p href="#!" class="secondary-content"><i class="material-icons">grade</i> 4.7</p>
      </li>
    </ul>

  </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static_no_cache 'js/problem.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static_extra %}
{% block navHome %}active{% endblock %}
{% block content %}

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center grey-text text-darken-4">AI Playground</h1>
    <div class="row center">
      <h5 class="header col s12 light">It is more than coding.</h5>
    </div>
    <div class="row center">
      <a href="{% url 'sign' %}" class="btn-large waves-effect waves-light pink">
        Get Started</a>
    </div>
    <br><br>
    <br>
    <div class="divider"></div>
    <br>
  </div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s8 offset-s2 m6 l5">
        <div class="icon-block">
          <h2 class="center indigo-text"><i class="material-icons md-36">assignment</i></h2>
          <h5 class="center">Traditional Problems</h5>
          <p class="justify">From a traditional view, yes, this is an <b>Online Judge</b>. You will definitely find some interesting problems here.
            Judges here are usually friendly. They bear possible errors, and give you the fairest judge result.
            Hope you have fun and have no frustrating bugs.</p>
        </div>
      </div>

      <div class="col s8 offset-s2 m6 l5 offset-l2">
        <div class="icon-block">
          <h2 class="center indigo-text"><i class="material-icons md-36">group</i></h2>
          <h5 class="center">Combat Problems</h5>
          <p class="justify">The most exciting part, however, is <b>combat problems</b>. Usually, these problems do not have a definitely right and wrong.
            The more score you are gaining, the better. And usually, these problems involve two players or even more play together. So judge
            will run each of them and find which program seems to be the best.</p>
        </div>
      </div>
    </div>

  </div>
  <br>

  <div class="divider"></div>

  <div class="section">
    <div class="row">
      <div class="col s10 offset-s1 m4">
        <div class="icon-block">
          <h2 class="center pink-text"><i class="material-icons">public</i></h2>
          <h5 class="center">Open</h5>
          <p class="justify">If you want to add a problem to the problem list, why not? As long as you have done a certain number of problems
            to show you are a <b>real</b> problem settler, you are most welcome to do that. Also, you can hold public or private contests, based
            on your own problems.</p>
        </div>
      </div>

      <div class="col s10 offset-s1 m4">
        <div class="icon-block">
          <h2 class="center pink-text"><i class="material-icons">code</i></h2>
          <h5 class="center">Simpler</h5>
          <p class="justify">Making coding simpler has always been our dream. In the long history, the choices of packages on online judge is strictly restricted.
            Well, we decided to change that. You can access the package source, so that you don't have to copy things down from Internet or from
            some books. We hope that this will be helpful.</p>
        </div>
      </div>

      <div class="col s10 offset-s1 m4">
        <div class="icon-block">
          <h2 class="center pink-text"><i class="material-icons">trending_up</i></h2>
          <h5 class="center">Better</h5>
          <p class="justify">You know what they say - there is the best, but the best is not always the best; there is better; there is always
            better. The <b>real</b> difference between a traditional online judge and us is that we do not have a so-called 'accepted', That is
            to say, to be the top of the ranklist, there is always something you can do.</p>
        </div>
      </div>
    </div>
  </div>

  <br><br>
</div>


{% endblock %}

{% block script %}

<script src="{% static_no_cache 'js/home.js' %}"></script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

  <div class="bd-masthead">
    <div class="container">
      <span class="bd-booticon">AI</span>
      <h1>What is AI Playground?</h1>
      <p class="lead mb-2">AI Playground is a platform where you can submit your program and compete with others.<br/>
                          You will have fun mindstorming, coding and sharing ideas.</p>
      <button class="btn btn-outline-primary btn-lg">Get started</button>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4"><div class="jumbotron bg-faded">
      <h2>Contest</h2>
      <p class="lead">Submit your AI program and compete!</p>
      <a class="btn btn-primary btn-block mb-2" href="{% url 'problist' %}" role="button">Try it &raquo;</a>
    </div></div>

    <div class="col-md-4"><div class="jumbotron bg-faded">
      <h2>Challenge</h2>
      <p class="lead">Are you more clever than those dumb programs?</p>
      <a class="btn btn-primary btn-block mb-2" href="challenge.php" role="button">Beat it &raquo;</a>
    </div></div>

    <div class="col-md-4"><div class="jumbotron bg-faded">
      <h2>Headline</h2>
      <p class="lead"><strong>[UPD 1 hour ago]</strong> zerol's program has successfully defeated ultmaster, the champion of Gobang. Orz!</p>
      <a class="btn btn-primary btn-block mb-2" href="status.php" role="button">More news in the air &raquo;</a>
    </div></div>
  </div>

{% endblock %}

{% block script %}
    <script>
        function show_message(json) {
            var user_error_message = $('#user_error_message');
            var user_success_message = $('#user_success_message');
            if (json['error'] == 1) {
                user_success_message.hide();
                user_error_message.html(json['message']);
                user_error_message.show(500);
            } else {
                user_error_message.hide();
                user_success_message.html(json['message']);
                user_success_message.show(500);
                setTimeout(function() { location.reload(); }, 3000);
            }
        }

        $(document).ready(function() {
            $('#main_login').click(function() {
                //alert('Hello');
                var data = $('#user_form').serialize();
                $.getJSON("{% url 'login' %}", data, function(json) {
                    show_message(json);
                    $('#main_login').blur();
                });
            });
            $('#main_register').click(function() {
                var data = $('#user_form').serialize();
                $.getJSON("{% url 'register' %}", data, function(json) {
                    show_message(json);
                    $('#main_register').blur();
                });
            });

        });
    </script>

{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% block content %}

<div class="bd-pageheader">
  <div class="container">
    <h1>Settings</h1>
  </div>
</div>

<div class="container">
  <ul class="nav nav-tabs mb-2" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#profile" role="tab">Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#security" role="tab">Security</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#notification" role="tab">Notification</a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane fade in active" id="profile" role="tabpanel">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <form action="{% url "settings:profile" %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group row">
            <div class="col-sm-3 col-form-label set-label">{{ field.label_tag }}</div>
            <div class="col-sm-9">{{ field }}</div>
          </div>
          {% for error in field.errors %}
            <div class="alert alert-info">{{ error }}</div>    <!-- TODO too fat -->
          {% endfor %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    <div class="tab-pane fade" id="security" role="tabpanel">bbb</div>
    <div class="tab-pane fade" id="notification" role="tabpanel">ccc</div>
  </div>
</div>
{% endblock %}

templates/sign.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static_extra %}
{% block css %}
<link href="{% static_no_cache 'css/user.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="section">
  <div class="container" id="sign-container">
    <div class="row">
      <nav class="transparent z-depth-0 col s12 m8 offset-m2 l6 offset-l3">
        <div class="nav-content">
          <ul class="tabs tabs-transparent inverse">
            <li class="tab"><a @click="toggle('in')" :class="signInActive">Sign In</a></li>
            <li class="tab"><a @click="toggle('up')" :class="signUpActive">Sign Up</a></li>
          </ul>
        </div>
      </nav>

      <signin v-show="signInActive"></signin>

      <signup v-show="signUpActive"></signup>


    </div>
  </div>
</div>

<template id="sign-input-template">
  <div class="input-field">
    <input @focus="clearErrorMessage" class="validate" :type="inputType" :name="inputName" required>
    <label :for="inputName" :data-error="errorMessage">[[ placeholder ]]</label>
  </div>
</template>

<template id="sign-in-template">
  <div class="col s12 m8 offset-m2 l6 offset-l3 sign-form">
    <form id="sign-in-form" v-on:submit.prevent="submit">
      {% csrf_token %}
      <sign-input placeholder="Username" input-name="username" input-type="text" data-error="Invalid username."></sign-input>
      <sign-input placeholder="Password" input-name="password" input-type="password" data-error="Invalid password."></sign-input>
      <div class="row">
        <div class="col s12 center">
          <button class="btn-submit btn-large pink waves-effect waves-light">
            Sign In
          </button>
        </div>
      </div>
    </form>
  </div>
</template>

<template id="sign-up-template">
  <div class="col s12 m8 offset-m2 l6 offset-l3 sign-form">
    <form id="sign-up-form" v-on:submit.prevent="submit">
      {% csrf_token %}
      <sign-input placeholder="Email" input-name="email" input-type="email" data-error="Invalid email address."></sign-input>
      <sign-input placeholder="Username" input-name="username" input-type="text" data-error="Invalid username."></sign-input>
      <sign-input placeholder="Password" input-name="password" input-type="password" data-error="Invalid password."></sign-input>
      <div class="row">
        <div class="col s12 center">
          <button class="btn-submit btn-large pink waves-effect waves-light">
            Sign Up
          </button>
        </div>
      </div>
    </form>
  </div>
</template>

{% endblock %}

{% block script %}

<script src="{% static_no_cache 'js/user.js' %}"></script>

{% endblock %}

templates/submission.html
{% extends 'base.html' %}
{% block content %}

<div class="bd-pageheader">
  <div class="container">
    <h1>Submission #{{ submission.id }}</h1>
    <p class="lead">Solution by {{ submission.author }}</p>
  </div>
</div>
<div class="container">

    <table class="table table-sm">
      <thead>
      <th>#</th>
      <th>Problem</th>
      <th>Author</th>
      <th>Language</th>
      <th>Status</th>
      <th>Rating</th>
      </thead>
      <tbody>
      <tr>
        <td scope="row">{{ submission.id }}</td>
        <td><a href="{% url 'problem' submission.problem.id %}">{{ submission.problem }}</a></td>
        <td><a href="#">{{ submission.author }}</a></td>
        <td>{{ submission.get_language_display }}</td>
        <td>{{ submission.get_verdict_display }}</td>
        <td>{{ submission.rating }}</td>
      </tr>
      </tbody>
    </table>

  <pre class="px-2 py-1">{{ submission.code }}</pre>
  <p class="text-xs-right text-muted"><strong>Code Length:</strong> {{ submission.code | length }} bytes<br/>
     {{ submission.submit_time }}</p>

<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </a>
      </h5>
    </div>

    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Collapsible Group Item #2
        </a>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="card-block">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Collapsible Group Item #3
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="card-block">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>

</div>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% block content %}
  <div id="app"></div>
{% endblock %}

{% block script %}

{% render_bundle 'index' %}

{% endblock %}